name: Selenium Grid
description: |
	Deploy a selenium grid with a centralized hub and as many nodes as you need
version: 1
category: Testing
maintainer: Benjamin Audren <benjamin.audren@gmail.com>
license: MIT
projectURL: https://github.com/baudren/selenium-grid-rancher-template
